# Generated by Django 4.0.4 on 2022-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='identity',
            field=models.IntegerField(),
        ),
    ]
