# Generated by Django 4.0.4 on 2022-04-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0003_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=100)),
            ],
        ),
    ]
