# Generated by Django 4.0.4 on 2022-04-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0004_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidentity', models.IntegerField()),
                ('choice', models.CharField(max_length=5)),
            ],
        ),
    ]
